name: narrative_data_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

assets:
    - assets/Cleaned_Narrative_DAG.json

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.3
  google_generative_ai: ^0.4.0
  file_picker: ^8.0.0
  http: ^1.2.0
  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/Cleaned_Narrative_DAG.json