/// Icon paths for skills (generated from skills.json). The file name
/// matches the skill's id exactly.
class SkillIcons {
  SkillIcons._();

  /// The asset path for a skill given its id, e.g.
  /// SkillIcons.pathFor("fireball") -> assets/icons/skills/fireball.png
  static String pathFor(String skillId) => 'assets/icons/skills/$skillId.png';

  /// Every skill id with a generated icon -- checked at the call site so a
  /// future skill without a matching PNG falls back gracefully instead of
  /// hitting a broken-asset placeholder.
  static const List<String> allIds = [
    'adrenaline_surge',
    'arcane_convergence',
    'archon_eclipse',
    'bastion_of_stone',
    'battle_trance',
    'blazing_shadow',
    'bulwark_stance',
    'cauterize_wound',
    'celestial_ward',
    'cleric_holy_light',
    'cleric_prayer',
    'cleric_purify',
    'cleric_revive_prayer',
    'cleric_sanctuary',
    'cleric_smite',
    'disorienting_pulse',
    'dwarf_forgeheart',
    'dwarf_hammer_blow',
    'dwarf_stoneskin',
    'elf_arcane_focus',
    'elf_keen_eye',
    'elf_moonlight_step',
    'final_stand',
    'fireball',
    'focus_mind',
    'frigid_grip',
    'golem_meltdown',
    'guard_break',
    'heavy_attack',
    'human_diplomacy',
    'human_quick_study',
    'human_resolve',
    'improvised_strike',
    'infernal_pact',
    'inner_fire',
    'iron_will',
    'lucky_strike',
    'mage_arcane_missile',
    'mage_frost_nova',
    'mage_channel',
    'mage_mana_shield',
    'mage_meteor',
    'mage_teleport_strike',
    'manifestation_many_faces',
    'matriarch_brood_call',
    'mending_touch',
    'molten_backlash',
    'orc_berserk_rage',
    'orc_bloodlust',
    'orc_savage_cleave',
    'plague_bite',
    'power_strike',
    'precision_thrust',
    'quick_heal',
    'radiant_judgment',
    'rallying_shout',
    'ranger_aimed_shot',
    'ranger_beast_bond',
    'ranger_camouflage',
    'ranger_multi_shot',
    'ranger_trap_set',
    'rogue_backstab',
    'rogue_poison_blade',
    'rogue_quick_pockets',
    'rogue_shadow_clone',
    'rogue_smoke_bomb',
    'ruthless_edge',
    'second_chance',
    'second_wind',
    'shadow_step',
    'sovereign_unmaking',
    'stalker_ambush',
    'steady_aim',
    'stone_resolve',
    'unbreakable_will',
    'venomous_ambush',
    'void_blast',
    'void_drain',
    'voidkin_entropy_touch',
    'voidkin_starless_gaze',
    'voidkin_umbral_veil',
    'warcry',
    'warden_bone_storm',
    'warrior_execute',
    'warrior_iron_stance',
    'warrior_rally_cry',
    'warrior_shield_bash',
    'warrior_whirlwind',
    'wrath_of_dawn',
    'zealot_martyrdom',
    'zealous_conviction',
  ];
}
